car_drive/Edrive/urls.py
from django.urls import path
from .views import (
    UserView, UserLoginView, RegistUserView, HomeView,RecordsView,
    TargetFuelView, MyCarView,  MyPageView, MyPageEditView, EcoCarSiteView, MyCarDetailView, PortfolioView,LogoutView
)
app_name = 'Edrive'

urlpatterns = [
    path('start/',UserView.as_view(), name='start'),
    path('login/',UserLoginView.as_view(), name='login'),
    path('regist/',RegistUserView.as_view(), name='regist'),
    path('home/',HomeView.as_view(), name = 'home'),
    path('my_car/<int:pk>',MyCarView.as_view(), name = 'my_car'),
    path('records/<int:pk>/',RecordsView.as_view(), name = 'records'),
    path('target_fuelefficiency/<int:pk>',TargetFuelView.as_view(), name = 'target_fuelefficiency'),
    path('mycar_detail/<int:pk>',MyCarDetailView.as_view(), name = 'mycar_detail'),
    path('mypage/<int:pk>',MyPageView.as_view(), name = 'mypage'),
    path('mypage_edit/<int:pk>',MyPageEditView.as_view(), name = 'mypage_edit'),
    path('eco_car_site/',EcoCarSiteView.as_view(), name = 'eco_car_site'),
    path('portfolio/',PortfolioView.as_view(), name = 'portfolio'),
    path('logout/',LogoutView.as_view(), name = 'logout'),  # ルート URL にアクセス時に PortfolioView を表示
]

car_drive/car_drive/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from Edrive.views import PortfolioView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('Edrive/', include('Edrive.urls')),
    path('portfolio/', PortfolioView.as_view(), name='portfolio'),
    path('', PortfolioView.as_view(), name='root_portfolio'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

car_drive/templates/eco_car_site.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Home</title>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
   </head>
  
   <body>
       <header class="header-container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'Edrive:my_car' user.pk %}">マイカー</a>
        <a class="navbar-brand" href="{% url 'Edrive:mypage' user.pk %}">マイページ</a>
        <div class="logo">
        <a href="{% url 'Edrive:home' %}" class="home-link">
             <img src = "{% get_media_prefix %}shinryoku.png"  alt = "ホーム">
             <p>HOME</p>
        </a>
        </div>
        <a class="navbar-brand" href="{% url 'Edrive:eco_car_site' %}">エコカー関連サイト</a>
        <a class="navbar-brand" href="{% url 'Edrive:logout' %}">ログアウト</a>
      </nav>
      </header>
      {% block content %}{% endblock %}
    <div class="link-container">
      <ul>

      <li><a href = "https://rentacar.carlifestadium.com/blog/smart/2631/" target="_blank">【ハイブリッドvsガソリン】何キロ走れば元を取れる？簡単な計算表付で比較してみた|カーチップス</a></li>
        
      <li><a href ="https://rakunori.idex.co.jp/column/column_45.html#:~:text=%E3%81%9D%E3%82%8C%E3%81%A7%E3%81%AF%E3%80%81%E5%A4%9A%E3%81%8F%E3%81%AE%E4%BA%BA%E3%81%8C%E6%A4%9C%E8%A8%8E%E3%81%97%E3%81%A6%E3%81%84%E3%82%8B%E3%80%8C%E3%82%AC%E3%82%BD%E3%83%AA%E3%83%B3%E8%BB%8A%E4%BB%A5%E5%A4%96%E3%80%8D%E3%81%A8%E3%81%AF%E3%80%81%E5%85%B7%E4%BD%93%E7%9A%84%E3%81%AB%E3%81%AF%E3%81%A9%E3%81%AE%E3%82%BF%E3%82%A4%E3%83%97%E3%81%AA%E3%81%AE%E3%81%A7%E3%81%97%E3%82%87%E3%81%86%E3%81%8B%E3%80%82,%E7%A8%AE%E9%A1%9E%E5%88%A5%E3%81%AE%E5%9B%9E%E7%AD%94%E3%81%AB%E3%82%88%E3%82%8B%E3%81%A8%E3%80%81%E3%83%80%E3%83%B3%E3%83%88%E3%83%84%E3%81%AE%E3%83%88%E3%83%83%E3%83%97%E3%81%AF%E3%80%8C%E3%83%8F%E3%82%A4%E3%83%96%E3%83%AA%E3%83%83%E3%83%89%E8%BB%8A%E3%80%8D%E3%81%A771%EF%BC%85%E3%80%81%E6%AC%A1%E3%81%84%E3%81%A7%E3%80%8CEV%E3%80%8D%E3%81%8C31%EF%BC%85%E3%80%81%E3%80%8C%E3%83%87%E3%82%A3%E3%83%BC%E3%82%BC%E3%83%AB%E8%BB%8A%E3%80%8D%E3%81%8C25%EF%BC%85%E3%80%81%20%E3%80%8C%E3%83%97%E3%83%A9%E3%82%B0%E3%82%A4%E3%83%B3%E3%83%8F%E3%82%A4%E3%83%96%E3%83%AA%E3%83%83%E3%83%89%E8%BB%8A%E3%80%8D%E3%81%8C14%EF%BC%85%E3%80%81%E3%80%8C%E6%B0%B4%E7%B4%A0%E8%87%AA%E5%8B%95%E8%BB%8A%E3%80%8D%E3%81%8C7%EF%BC%85%E3%81%A8%E3%81%84%E3%81%86%E7%B5%90%E6%9E%9C%E3%81%AB%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%97%E3%81%9F%EF%BC%88%E8%A4%87%E6%95%B0%E5%9B%9E%E7%AD%94%EF%BC%89%E3%80%82" target="_blank">EVやハイブリッド車はまだ早い!?ガソリン車以外を選ぶホンネとは|コラム一覧|「身近なSSが見守る、安心・気軽なマイカーリース」マイカーリースラクのり</a></li>
        
      <li><a href ="https://ondankataisaku.env.go.jp/decokatsu/ecodriver/point/" target="_blank">エコドライブ10のすすめ|エコドライブ|COOL CHOICE 未来のために、いま選ぼう。</a></li>
      </ul>
  </body>
</html>

car_drive/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Home</title>
      <link rel="stylesheet" href="{% static 'css/home.css' %}">
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.min.js"></script>
   </head>
   
  
   <body>
       
       <div class="parallelogram">
        <h1>5eDRIVE</h1>
        </div>
        <header class="header-container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'Edrive:my_car' user.pk %}">マイカー</a>
        <a class="navbar-brand" href="{% url 'Edrive:mypage' user.pk %}">マイページ</a>
        <div class="logo">
        <a href="{% url 'Edrive:home' %}" class="home-link">
             <img src = "{% get_media_prefix %}shinryoku.png"  alt = "ホーム">
             <p>HOME</p>
        </a>
        </div>
        <a class="navbar-brand" href="{% url 'Edrive:eco_car_site' %}">エコカー関連サイト</a>
        <a class="navbar-brand" href="{% url 'Edrive:logout' %}">ログアウト</a>
      </nav>
      </header>
      {% block content %}{% endblock %}

    <div class="achievement-info">
    <div class="nav-links">
    <a class="navbar-brand" href="{% url 'Edrive:records' user.pk %}">燃費入力</a>
    <a class="navbar-b" href="{% url 'Edrive:target_fuelefficiency' user.pk %}">目標燃費量入力</a>
    </div>
    <div class="shape"><img src = "{% get_media_prefix %}driver.png"  alt = "しずく">
    </div>
    <p class="achievement-text">あと{{ remaining_targets }}回目標達成<br>でレベルアップ</p>
    
    
    <p>現在のドライバーレベル<span class="current-level">{{ user.driver_level }}</span></p>
    
    </div>
    <div class="achievement-container">
        <div class="target-achievement">
            <h4>目標燃費量</h4>
    {% if my_cars %}
     {% for my_car in my_cars %}
       {% if my_car.target_fuel_efficiency %}
         <div class="value">{{ my_car.target_fuel_efficiency }}km/L</div>
         {% else %}
        <div class="value">未登録</div>
         {% endif %}
    {% endfor %}
    {% else %}
    <div class="value">未登録</div>
    {% endif %}

    </div>
        <div class="actual-achievement">
            <h4>実績燃費量</h4>
       {% if latest_fuel_record %}
        <div class="value">{{ latest_fuel_record.fuel_efficiency|floatformat:1 }}km/L</div>
       {% else %}
        <div class="value">未登録</div>
       {% endif %}
         </div>
   <div class="you">
   <img src = "{% get_media_prefix %}you.png"  alt = "葉">
   </div>
   <canvas id="fuelEfficiencyChart" ></canvas>
    <script>
        var ctx = document.getElementById('fuelEfficiencyChart').getContext('2d');
        var targetEfficiencyData = JSON.parse('{{ target_efficiency_data|escapejs }}');
        var achievedEfficiencyData = JSON.parse('{{ achieved_efficiency_data|escapejs }}');
        var dates = JSON.parse('{{ dates|escapejs }}');
        var averageFuelEfficiencyAll = JSON.parse('{{ average_fuel_efficiency_all|escapejs }}');
        var averageFuel = JSON.parse('{{ average_fuel|escapejs }}');
        
        var datasets = [
            {
                label: '目標燃費',
                data: targetEfficiencyData,
                borderColor: 'blue',
                fill: false
            },
            {
                label: '実績燃費',
                data: achievedEfficiencyData,
                borderColor: 'red',
                fill: false
            }
        ];

        averageFuel.forEach(function(car) {
        let borderColor;

        if (car.engine_type === 'gasoline') {
            borderColor = 'orange';  // ガソリン車の平均燃費
        } else if (car.engine_type === 'hybrid') {
            borderColor = 'green';  // ハイブリッド車の平均燃費
        } else {
            return;  // ガソリン車やハイブリッド車でない場合はスキップ
        }

        datasets.push({
            label: car.car_model_name + ' 平均燃費',
            data: Array(dates.length).fill(car.average_fuel_efficiency),
            borderColor: borderColor,
            borderDash: [10, 5],
            fill: false,
        });
       });

        

        if (averageFuelEfficiencyAll !== null) {
                    datasets.push({
                        label: '同じ車種の全体平均燃費',
                        data: Array(dates.length).fill(averageFuelEfficiencyAll),
                        borderColor: 'purple',
                        borderDash: [10, 5],
                        fill: false,
                });
            }

        var chart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: dates,
                datasets: datasets
            },
            options: {
                legend: {
                    labels: {
                        fontSize: 20 // 凡例（ラベル）の文字サイズを設定
                    }
                  },
                title: {
                        display: true,
                        text: '燃費量',
                        fontSize: 30
                        },  
                        scales: {
                           xAxes: [{
                             scaleLabel: {
                                display: true,
                                labelString: '日付',
                                fontSize: 30  // x軸のラベルのフォントサイズ
                             },
                            ticks: {
                                  fontSize: 30 // x軸のティックラベルのフォントサイズ
                              }
                             }],
                           yAxes: [{
                            scaleLabel: {
                                 display: true,
                                 labelString: '燃費 (km/L)',
                                 fontSize: 30  // y軸のラベルのフォントサイズ
                                  },
                               ticks: {
                                    fontSize: 30 // y軸のティックラベルのフォントサイズ
                                       }
                                     }]
                                 }
                                }
                            });
    </script>
   </div>
   <div class="you">
   <img src = "{% get_media_prefix %}you.png"  alt = "葉">
   </div>  
  
</div>
</body>
</html>
   

car_drive/templates/my_car.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>my_car</title>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
   </head>
  
   <body>
       <header class="header-container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'Edrive:my_car' user.pk %}">マイカー</a>
        <a class="navbar-brand" href="{% url 'Edrive:mypage' user.pk %}">マイページ</a>
        <div class="logo">
        <a href="{% url 'Edrive:home' %}" class="home-link">
             <img src = "{% get_media_prefix %}shinryoku.png"  alt = "ホーム">
             <p>HOME</p>
        </a>
        </div>
        <a class="navbar-brand" href="{% url 'Edrive:eco_car_site' %}">エコカー関連サイト</a>
        <a class="navbar-brand" href="{% url 'Edrive:logout' %}">ログアウト</a>
      </nav>
      </header>
      {% block content %}{% endblock %}

        <div class="car-info">
        <h3>マイカー登録</h3>
            {% if car_model_jp %}
            <table class="table table-bordered">
            <tbody>
                <tr>
                    <td style="width: 30%;">メーカー</td>
                    <td style="width: 30%;">{{ manufacturer_jp }}</td>
                </tr>
                <tr>
                    <td>車種</td>
                    <td>{{ car_model_jp }}</td>
                </tr>
                <tr>
                    <td>エンジン</td>
                    <td>{{ engine_type_jp }}</td>
                </tr>
                <tr>
                    <td>購入年月</td>
                    <td>{{ mycars_instance.purchase_on }}</td>
                </tr>
            </tbody>
            </table>
        {% else %}
        <h3>マイカーを登録してください</h3>
        {% endif %}
        <nav>
          <a class="navbar-brand" href="{% url 'Edrive:mycar_detail' user.pk %}">変更</a>
        </nav>
        </div>
    </body>
</html>
   

car_drive/templates/mycar_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>detail</title>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
   </head>
  
   <body>
       <header class="header-container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'Edrive:my_car' user.pk %}">マイカー</a>
        <a class="navbar-brand" href="{% url 'Edrive:mypage' user.pk %}">マイページ</a>
        <div class="logo">
        <a href="{% url 'Edrive:home' %}" class="home-link">
             <img src = "{% get_media_prefix %}shinryoku.png"  alt = "ホーム">
             <p>HOME</p>
        </a>
        </div>
        <a class="navbar-brand" href="{% url 'Edrive:eco_car_site' %}">エコカー関連サイト</a>
        <a class="navbar-brand" href="{% url 'Edrive:logout' %}">ログアウト</a>
      </nav>
      </header>
      {% block content %}{% endblock %}

    <div class="detail-container">
       <form method="POST" action="">
   {% csrf_token %}
   <div class="form-group">
                {{ form1.manufacturer_name.label_tag }}
                {{ form1.manufacturer_name }}
            </div>
            <div class="form-group">
                {{ form1.car_model.label_tag }}
                {{ form1.car_model }}
            </div>

            
            <div class="form-group">
                {{ form1.purchase_on.label_tag }}
                {{ form1.purchase_on }}
            </div>
            <div class="btn-container">
   <input type="submit" value="更新" class="btn">
</form>

      <nav class="detail-navbar">
          <a class="navbar-brand" href="{% url 'Edrive:my_car' user.pk %}">戻る</a>
      </nav>
      </div>
    </div>
    </body>
</html>

car_drive/templates/mypage.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Home</title>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
   </head>
  
   <body>
       <header class="header-container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'Edrive:my_car' user.pk %}">マイカー</a>
        <a class="navbar-brand" href="{% url 'Edrive:mypage' user.pk %}">マイページ</a>
        <div class="logo">
        <a href="{% url 'Edrive:home' %}" class="home-link">
             <img src = "{% get_media_prefix %}shinryoku.png"  alt = "ホーム">
             <p>HOME</p>
        </a>
        </div>
        <a class="navbar-brand" href="{% url 'Edrive:eco_car_site' %}">エコカー関連サイト</a>
        <a class="navbar-brand" href="{% url 'Edrive:logout' %}">ログアウト</a>
      </nav>
      </header>
      {% block content %}{% endblock %}
      <style>
        .divider {
            border-top: 2px solid black;
            margin-top: 10px;
            margin-bottom: 10px;
        }
    </style>
   </head>
  <body class="my_page">
    <h3>マイページ</h3>
    <h4>名前/ニックネーム:{{ user.user_name|default:"未設定"  }}</h4>
    <h4>運転免許証 次回:{{ user.licence_expiry_on|default:"未設定" }}</h4>
    <h4>オイル交換 次回:{{ mycars_instance.next_oil_change_on|default:"未設定" }}</h4>
    <h4>車検 次回:{{ mycars_instance.next_inspection_on|default:"未設定" }}
    <a class="navbar-b" href="{% url 'Edrive:mypage_edit' user.pk %}">編集</a>
    </h4>
    

    <hr class = "divider">
    
    <h4>現在のドライバーレベル <span class="driver-level-box">{{ user.driver_level }}</span></h4>
    </body>
</html>

car_drive/templates/mypage_edit.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>mypage_edit</title>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
   </head>
  
   <body>
       <header class="header-container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'Edrive:my_car' user.pk %}">マイカー</a>
        <a class="navbar-brand" href="{% url 'Edrive:mypage' user.pk %}">マイページ</a>
        <div class="logo">
        <a href="{% url 'Edrive:home' %}" class="home-link">
             <img src = "{% get_media_prefix %}shinryoku.png"  alt = "ホーム">
             <p>HOME</p>
        </a>
        </div>
        <a class="navbar-brand" href="{% url 'Edrive:eco_car_site' %}">エコカー関連サイト</a>
        <a class="navbar-brand" href="{% url 'Edrive:logout' %}">ログアウト</a>
      </nav>
      </header>
      {% block content %}{% endblock %}

      <div class="edit">
       <form method="POST">
       {% csrf_token %}
        <div class="form-group">
            {{ form1.user_name.label_tag }}
            {{ form1.user_name }}
        </div>
        <div class="form-group">
            {{ form1.licence_expiry_on.label_tag }}
            {{ form1.licence_expiry_on }}
        </div>
        <div class="form-group">
            {{ form2.next_oil_change_on.label_tag }}
            {{ form2.next_oil_change_on }}
        </div>
        <div class="form-group">
            {{ form2.next_inspection_on.label_tag }}
            {{ form2.next_inspection_on }}
        </div>
   
        <input type="submit" value="更新" class="btn">
       </form>
       <a class="navbar-brand" href="{% url 'Edrive:mypage' user.pk%}">戻る</a>

      </div>
    </body>
    </html>

car_drive/templates/records.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>FuelRecords</title>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
   </head>
  
   <body>
       <header class="header-container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'Edrive:my_car' user.pk %}">マイカー</a>
        <a class="navbar-brand" href="{% url 'Edrive:mypage' user.pk %}">マイページ</a>
        <div class="logo">
        <a href="{% url 'Edrive:home' %}" class="home-link">
             <img src = "{% get_media_prefix %}shinryoku.png"  alt = "ホーム">
             <p>HOME</p>
        </a>
        </div>
        <a class="navbar-brand" href="{% url 'Edrive:eco_car_site' %}">エコカー関連サイト</a>
        <a class="navbar-brand" href="{% url 'Edrive:logout' %}">ログアウト</a>
      </nav>
      </header>
      {% block content %}{% endblock %}

  <div class="records">
  
  <nav>
  {% if mycar_registered %}
   <form method="POST">
   {% csrf_token %}
            <div class="form-group">
                {{ form.date.label_tag }}
                {{ form.date }}
            </div>
            <div class="form-group">
                {{ form.distance.label_tag }}
                {{ form.distance }}
            </div>
            <div class="form-group">
                {{ form.fuel_amount.label_tag }}
                {{ form.fuel_amount }}
            </div>
   <input type="submit" value="保存">
        </form>
   {% else %}
    <!-- マイカーが登録されていない場合にリンクを表示 -->
    <p>マイカーが登録されていません。まずはマイカーを登録してください。</p>
    <!-- URLのみを表示 -->
    <p><a href="{% url 'Edrive:mycar_detail' user.pk %}">クリックするとマイカー登録画面に遷移します</a></p>
    {% endif %}
        
        {% if date %}
            <h2>Formatted DateTime: {{ created_at }}</h2>
        {% endif %}
    <a class="navbar-brand" href="{% url 'Edrive:home' %}">戻る</a>
    </nav>
    </div>
<div class="records-container">
        <div class="car-info">
            <table border='1'>
      <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>日付</th>
                <th>走行距離(km)</th>
                <th>給油量(L)</th>
                <th>燃費量(km/L)</th>
                <th>削除</th>
            </tr>
               
        </thead>
            <tbody>
            {% for record in fuel_records %}
                <tr>
                    <td>{{ record.id }}</td>
                    <td>{{ record.date|date:"Y年n月j日" }}</td>
                    <td>{{ record.distance }}km</td>
                    <td>{{ record.fuel_amount }}L</td>
                    <td>{{ record.fuel_efficiency|floatformat:1 }}km/L</td>
                    <td>
                    <form method="post" style="display:inline;">
                        {% csrf_token %}
                        <input type="hidden" name="delete_record_id" value="{{ record.id }}">
                        <button type="submit">削除</button>
                      </form>
                    </td>
                </tr>
               {% endfor %}
            </tbody>
     </table>
</div>
</body>
</html>

 
 

car_drive/templates/start.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Home</title>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
   </head>
   <body class="start-page">
      <h1>5eDRIVEにようこそ!</h1>
<h2>燃費計算で環境にやさしいドライブを</h2>

      <nav>
        
        <a class="navbar-brand" href="{% url 'Edrive:login' %}">ログイン</a>
        <a class="navbar-brand" href="{% url 'Edrive:regist' %}">新規登録</a>
        
      </nav>
      
   </body>
</html>

car_drive/templates/target_fuelefficiency.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>target_fuel_efficiency</title>
      <link rel="stylesheet" href="{% static 'css/style.css' %}">
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
   </head>
  
   <body>
       <header class="header-container">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'Edrive:my_car' user.pk %}">マイカー</a>
        <a class="navbar-brand" href="{% url 'Edrive:mypage' user.pk %}">マイページ</a>
        <div class="logo">
        <a href="{% url 'Edrive:home' %}" class="home-link">
             <img src = "{% get_media_prefix %}shinryoku.png"  alt = "ホーム">
             <p>HOME</p>
        </a>
        </div>
        <a class="navbar-brand" href="{% url 'Edrive:eco_car_site' %}">エコカー関連サイト</a>
        <a class="navbar-brand" href="{% url 'Edrive:logout' %}">ログアウト</a>
      </nav>
      </header>
      {% block content %}{% endblock %}
   
   <div class="target">
   {% if messages %}
    <div class="messages">
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
                {{ message }}
            </div>
        {% endfor %}
    </div>
   {% endif %}
   
   {% if my_car %}
   <h4>{{ my_car.car_model.car_model_name }}の平均燃費量 {{ my_car.car_model.average_fuel_efficiency }} km/L</h4>
   {% endif %}

<label for="target_fuel_efficiency">目標燃費量</label>
   <nav>
   {% if mycar_registered %}
        <form method="POST">
           {% csrf_token %}
         <div class="form-group">
           {{ form.as_p }}
           <span class="unit">km/L</span>
         </div>
   
   <button type="submit">更新</button>
        </form>
   {% else %}
    <!-- マイカーが登録されていない場合にリンクを表示 -->
    <p>マイカーが登録されていません。まずはマイカーを登録してください。</p>
    <!-- URLのみを表示 -->
    <p><a href="{% url 'Edrive:mycar_detail' user.pk %}">クリックするとマイカー登録画面に遷移します</a></p>
    {% endif %}
        
        <a class="navbar-brand" href="{% url 'Edrive:home' %}">戻る</a>
        
   </nav>
   </div>
   </body>
</html>